steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'setup-get-parameters-base64'
  script: |
    # save for next steps
    echo $(gcloud parametermanager parameters versions render $_ENVIRONMENT --parameter=$_PROJECT_NAME --location=global --format=json) \
      > /workspace/parameters-base64.json

    echo $(cat /workspace/parameters-base64.json)
  automapSubstitutions: true

- name: 'ghcr.io/jqlang/jq:latest'
  id: 'setup-extract-parameters'
  script: |
    echo $(ls -a)
    echo $(cat /workspace/parameters-base64.json)
    echo $(jq '.payload.data | @base64d | fromjson' /workspace/parameters-base64.json) \
      > /workspace/parameters.json
    echo $(cat /workspace/parameters.json)


- name: 'liquibase/liquibase:5.0'
  id: 'run-schema-migration'
  script: |
    # Install Liquibase

    # Execute sync script
    liquibase --version
  env:
    - 'LIQUIBASE_COMMAND_URL=$(DB_HOST)'
    - 'LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME=$(DB_NAME)'
    - 'LIQUIBASE_COMMAND_USERNAME=$(DB_USER)'
    - 'LIQUIBASE_COMMAND_PASSWORD=$(DB_PASSWORD)'
    - 'INSTALL_MYSQL=true'
substitutions:
  _PROJECT_NAME: sandbox-database # default value
  _ENVIRONMENT: dev # default value
options:
  logging: CLOUD_LOGGING_ONLY